---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trident-mcc-role-binding
  namespace: trident
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trident-mcc-role
subjects:
- kind: ServiceAccount
  name: trident-mcc-service-account
  namespace: trident
