apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trident-mcc
  name: trident-mcc
  namespace: trident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trident-mcc
  template:
    metadata:
      labels:
        app: trident-mcc
    spec:
      containers:
      - image: obassett/trident_mcc:0.1.1-beta
        name: trident-mcc
        ports:
        - name: liveness-port
          containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        - name: POLLING_INTERVAL
          value: "300"
        - name: TRIDENT_NAMESPACE
          value: "trident"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 2
      serviceAccountName: trident-mcc-service-account 

