---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-mcc-service-account
  namespace: trident

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trident-mcc-role
  namespace: trident
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - head
  - list
- apiGroups:
  - trident.netapp.io
  resources:
  - tridentbackendconfigs
  verbs:
  - get
  - head
  - patch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trident-mcc-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trident-mcc-role-binding
  namespace: trident
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trident-mcc-role
subjects:
- kind: ServiceAccount
  name: trident-mcc-service-account
  namespace: trident

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-mcc-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-mcc-clusterrole
subjects:
- kind: ServiceAccount
  name: trident-mcc-service-account
  namespace: trident

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trident-mcc
  name: trident-mcc
  namespace: trident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trident-mcc
  template:
    metadata:
      labels:
        app: trident-mcc
    spec:
      containers:
      - image: obassett/trident_mcc:0.1.1-beta
        name: trident-mcc
        ports:
        - name: liveness-port
          containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        - name: POLLING_INTERVAL
          value: "300"
        - name: TRIDENT_NAMESPACE
          value: "trident"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 2
      serviceAccountName: trident-mcc-service-account 
