---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-mcc-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-mcc-clusterrole
subjects:
- kind: ServiceAccount
  name: trident-mcc-service-account
  namespace: trident
